var BLOCKLY_TOOLBOX_XML = BLOCKLY_TOOLBOX_XML || Object.create(null);

/* BEGINNING BLOCKLY_TOOLBOX_XML ASSIGNMENT. DO NOT EDIT. USE BLOCKLY DEVTOOLS. */
BLOCKLY_TOOLBOX_XML['standard'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml" id="toolbox" style="display: none">'
 + '<category name="Robot Control" colour="#5b67a5">'
   + '<block type="run_forward"/>'
   + '<block type="run_backward"/>'
   + '<block type="turn_left"/>'
   + '<block type="turn_right"/>'
   + '<block type="turn_back"/>'
   + '<block type="stop"/>'
   + '<block type="led_blue">'
     + '<field name="Led_Blue_state">Led_Blue_ON</field>'
   + '</block>'
   + '<block type="led_green">'
     + '<field name="Led_Green_state">Led_Green_ON</field>'
   + '</block>'
   + '<block type="led_red">'
     + '<field name="Led_Red_state">Led_Red_ON</field>'
   + '</block>'
   + '<block type="light_show">'
     + '<field name="Light show_state">Light show_ON</field>'
   + '</block>'
   + '<block type="dancing_show_1">'
     + '<field name="Dancing_show_1_state">Dancing_show_1_ON</field>'
   + '</block>'
   + '<block type="dancing_show_2">'
     + '<field name="Dancing_show_2_state">Dancing_show_2_ON</field>'
   + '</block>'
   + '<block type="dancing_show_3">'
     + '<field name="Dancing_show_3_state">Dancing_show_3_ON</field>'
   + '</block>'
   + '<block type="turn_180_left"/>'
   + '<block type="turn_180_right"/>'
 + '</category>'
 + '<category name="Sensors" colour="#995ba5">'
   + '<block type="line_follower">'
     + '<field name="Line_follower_sensor_state">Line_follower_sensor_ON</field>'
   + '</block>'
   + '<block type="ultrasonic">'
     + '<field name="Ultrasonic_sensor_state">Ultrasonic_sensor_ON</field>'
   + '</block>'
   + '<block type="sound_sensor">'
     + '<field name="Sound _sensor_state">Sound_sensor_ON</field>'
   + '</block>'
   + '<block type="lights_sensor">'
     + '<field name="Lights_sensor_state">Lights_sensor_ON</field>'
   + '</block>'
 + '</category>'
 + '<category name="Logic" colour="#5b80a5">'
   + '<block type="controls_if"/>'
   + '<block type="logic_compare">'
     + '<field name="OP">EQ</field>'
   + '</block>'
   + '<block type="logic_operation">'
     + '<field name="OP">AND</field>'
   + '</block>'
   + '<block type="logic_negate"/>'
   + '<block type="logic_boolean">'
     + '<field name="BOOL">TRUE</field>'
   + '</block>'
   + '<block type="logic_null"/>'
   + '<block type="logic_ternary"/>'
 + '</category>'
 + '<category name="Loops" colour="#5ba55b">'
   + '<block type="controls_repeat_ext">'
     + '<value name="TIMES">'
       + '<shadow type="math_number">'
         + '<field name="NUM">10</field>'
       + '</shadow>'
     + '</value>'
   + '</block>'
   + '<block type="controls_whileUntil">'
     + '<field name="MODE">WHILE</field>'
   + '</block>'
   + '<block type="controls_for">'
     + '<field name="VAR" id="8CY0ZB25TmnjlGWo0w0.">i</field>'
     + '<value name="FROM">'
       + '<shadow type="math_number">'
         + '<field name="NUM">1</field>'
       + '</shadow>'
     + '</value>'
     + '<value name="TO">'
       + '<shadow type="math_number">'
         + '<field name="NUM">10</field>'
       + '</shadow>'
     + '</value>'
     + '<value name="BY">'
       + '<shadow type="math_number">'
         + '<field name="NUM">1</field>'
       + '</shadow>'
     + '</value>'
   + '</block>'
   + '<block type="controls_forEach">'
     + '<field name="VAR" id="*eSXuii/~.57~,2-2!wW">j</field>'
   + '</block>'
   + '<block type="controls_flow_statements" disabled="true">'
     + '<field name="FLOW">BREAK</field>'
   + '</block>'
 + '</category>'
 + '<category name="Variables" colour="#a55b80" custom="VARIABLE"/>'
+ '</xml>'
/* END BLOCKLY_TOOLBOX_XML ASSIGNMENT. DO NOT EDIT. */